POST http://localhost:3500/api/v1/user/register
content-type : application/json

{    
    "firstName"   : "Hemanth",
    "lastName"    : "Kambhampati",
    "email"       : "hemanth@gmail.com",
    "password"    : "1254",
    "phoneNo"     : "78945654", 
    "dateOfBirth" : "2000-09-23",
    "linkedInUrl" : "",
    "gitHubLink" : ""
}

###
GET http://localhost:3500/api/v1/user/jayanth2@gmail.com

###
PUT http://localhost:3500/api/v1/user/dbe77661-0f7a-4790-98da-732bbd67c4f4
Content-Type: application/json

{    
    "linkedInUrl" : "https://www.linkedin.com/in/jayanth-kambhampati-jk/",
    "gitHubLink" : "https://github.com/Jayanth930"
}

### 
DELETE http://localhost:3500/api/v1/user/dbe77661-0f7a-4790-98da-732bbd67c4f4
